# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export TERM="xterm-256color"

ZSH_THEME="ys"
plugins=(git tmux z colored-man-pages)

source $ZSH/oh-my-zsh.sh

# generate gitignore for py
alias ignore-py="wget https://raw.githubusercontent.com/github/gitignore/master/Python.gitignore"

# hack for OSX, when ctags installed via Homebrew is not found.
alias ctags='/usr/local/bin/ctags'

# use nvim instead of vim or vi
alias vim="nvim"
alias vi="nvim"

alias zshconfig="source ~/.zshrc"

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export PATH="/usr/local/opt/ruby/bin:$PATH"
export PATH="$HOME/.rbenv/bin:$PATH"
export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"
eval "$(rbenv init -)"
export PATH="/usr/local/opt/openjdk/bin:$PATH"

# use ag for fzf, reference from https://stackoverflow.com/questions/49052469/how-to-enable-ag-in-vim-fzf
export FZF_DEFAULT_COMMAND='ag --type f'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
